# Netlify configuration file
[build]
  publish = "dist"
  command = "npm run build"

# Redirect rules for API proxying
[[redirects]]
  from = "/tavusapi/*"
  to = "https://tavusapi.com/v2/:splat"
  status = 200
  force = true
  headers = {X-From = "Netlify"}

# SPA fallback - serve index.html for all routes that don't match files
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200